export interface GalleryClient {
  slug: string;
  name: string;
  images: string[];
}

// Images are hosted on UploadThing. Previously these were computed from
// /clients/... paths in public/, which no longer exists.
export const GALLERY_CLIENTS: GalleryClient[] = [
  {
    slug: "al-haram",
    name: "Al Haram Hotel",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoIZ59ehgTlInH4jDxaLqJQeB95UZd2krhAVtz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoM0lLi4TZRLtViv5Afw7zJWYyGn3c9m2o0OBb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoVkbfrf2LDzfdtyXCZN81pHvqeShcjA0KuroJ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1fL0KGI2GBDJ5EhnzkqvUHO8mpwZPgSfrXNA",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoq9vnrh9FwIsUvW8QANLp13Xq0OCzHZMBmtx6",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKotDURfUO5Ixie0E7aCrF3KzymN162BkLWTqpZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoxpm4Ti0TOhQuNsB92Z6qe1P4ViRmg8SUjMvA",
    ],
  },
  {
    slug: "alamein-marassi",
    name: "Alamein Marassi",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoXbhFpJN5abTocvqK4z6t2rpH3RJs5gkfuxhV",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoojaoUGy0HXODjURP6aWmnG1hlE9sNiypdvfr",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1t5ioLiI2GBDJ5EhnzkqvUHO8mpwZPgSfrXN",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKogVBvW6tYOp3EzU4ZnwhGQeDvAoaFf6CP5d2r",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKotLb09IEO5Ixie0E7aCrF3KzymN162BkLWTqp",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoBLUUeHJCRvDNA8b0LQJX9lSTUMyfKqerOI5h",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKofNqbzfzkqmPyJR9eSsVXWMGFItpbcDN5ioE2",
    ],
  },
  {
    slug: "cairomarriott",
    name: "Cairo Marriott",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoOn50PesuWs1Ma2rvQieRHxIVnN9wjJguqA8o",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWGePKPmKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo2gbuCCL1iUgwytplTZ3NzCdcXfuSGjHJW9FE",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoIOhkr0xgTlInH4jDxaLqJQeB95UZd2krhAVt",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoOnsmtSduWs1Ma2rvQieRHxIVnN9wjJguqA8o",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoUX5cjaNnJUl3GRyE2ih6jquKtSeAcVd4wI0Q",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1STaDWI2GBDJ5EhnzkqvUHO8mpwZPgSfrXNA",
    ],
  },
  {
    slug: "cairosheraton",
    name: "Cairo Sheraton",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoOnsobBRuWs1Ma2rvQieRHxIVnN9wjJguqA8o",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoR6ou7XePyYsPZxbmrvTI2RHMhcCD9fUa8tzp",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoj1EjvRaiuRMKHlSC2rzD93pJvBZknAFXTPtY",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoR6u8qRDPyYsPZxbmrvTI2RHMhcCD9fUa8tzp",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo60WgAJVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKocpT5tzf4AeVQ8aUkJ7fwnTPztEqiX0Sopd6m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoOEdrHDuWs1Ma2rvQieRHxIVnN9wjJguqA8oz",
    ],
  },
  {
    slug: "charmillion",
    name: "Charmillion Club",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoCZCjY6RHg31aI7PxDs8urdqY20hzBbpyQtiN",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoOtmENyuWs1Ma2rvQieRHxIVnN9wjJguqA8oz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoAH9t9O6Ti2uqtxQV7Ee8n0k5aI1Dy46YgFsK",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoIaQNj6gTlInH4jDxaLqJQeB95UZd2krhAVtz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoPVQTCwFA8LHR6kWZ0CQKy7r4ixEAe1VIODT3",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoCAtWaNFRHg31aI7PxDs8urdqY20hzBbpyQti",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKooOL8gQy0HXODjURP6aWmnG1hlE9sNiypdvfr",
    ],
  },
  {
    slug: "cleopatra-sharm",
    name: "Cleopatra Sharm",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoYseea9ioOTp43itjJGyYsV2PAS8ZzMKg7mXh",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoq1dvxFwIsUvW8QANLp13Xq0OCzHZMBmtx6n7",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKocDlzUBf4AeVQ8aUkJ7fwnTPztEqiX0Sopd6m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo5vZIwLQWX9d0YkhzgM3DoCNlpVOiZuU2JxAL",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoyQdt43NXrAYxzdmVjgpsP86LOhM5CKNnSiyt",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKok0dFk2UlS7g4a1nNLirvZYOyUWPKeJwcTmGX",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWAy3BAmKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
    ],
  },
  {
    slug: "cleopatra-sidi",
    name: "Cleopatra Sidi",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoctCiTFf4AeVQ8aUkJ7fwnTPztEqiX0Sopd6m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo5YirboQWX9d0YkhzgM3DoCNlpVOiZuU2JxAL",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo59XrnaQWX9d0YkhzgM3DoCNlpVOiZuU2JxAL",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoR6nCj9oPyYsPZxbmrvTI2RHMhcCD9fUa8tzp",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKooQc6Vvy0HXODjURP6aWmnG1hlE9sNiypdvfr",
    ],
  },
  {
    slug: "concord-sharm",
    name: "Concord Sharm",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoUYFQnxmNnJUl3GRyE2ih6jquKtSeAcVd4wI0",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoYPja3aioOTp43itjJGyYsV2PAS8ZzMKg7mXh",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKocRrzmGf4AeVQ8aUkJ7fwnTPztEqiX0Sopd6m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoCdv3bXRHg31aI7PxDs8urdqY20hzBbpyQtiN",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoiztM3iBRjXKozqUpZCEnigGSNYJtaDk9x7r4",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKomYgYxP8Az9kCU6bZsOnvlKwmIxLVWJ71fPoS",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoSgO7A73y8qcB6ekDnxL7t2AaHzC9ITRVMs1g",
    ],
  },
  {
    slug: "concordelsalam",
    name: "Concord El Salam",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoDynOTCKtTGSY50nBevl9JkXw2hLZPHzxc1IR",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoTPImgGrCIqDsOE6oZFJyjVC4Pbl5viu03Hkh",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKokHijA2UlS7g4a1nNLirvZYOyUWPKeJwcTmGX",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoydZBN7XrAYxzdmVjgpsP86LOhM5CKNnSiytb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoogiuIRy0HXODjURP6aWmnG1hlE9sNiypdvfr",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKof8FAzvkqmPyJR9eSsVXWMGFItpbcDN5ioE2B",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoPsOHGSA8LHR6kWZ0CQKy7r4ixEAe1VIODT3m",
    ],
  },
  {
    slug: "conradcairo",
    name: "Conrad Cairo",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoCCfv0qRHg31aI7PxDs8urdqY20hzBbpyQtiN",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKonX5SksVoF8WD2YLVgIT9zcahG1e34StEMdPw",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoKpUagijdUrwah2H7vRc96XWJjqbxQgB5t14A",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoCKCP9lRHg31aI7PxDs8urdqY20hzBbpyQtiN",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo4e97IEzF2OBDRcILbvgxCjsaZKW5i1kMGuf3",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoAd0ISz6Ti2uqtxQV7Ee8n0k5aI1Dy46YgFsK",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKooi9OaPy0HXODjURP6aWmnG1hlE9sNiypdvfr",
    ],
  },
  {
    slug: "coral-hurghada",
    name: "Coral Beach Hurghada",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo91kXlb4f5HBuWR7heLXoGzcMm1lS8y9rd462",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoRe8XchPyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoitEraKBRjXKozqUpZCEnigGSNYJtaDk9x7r4",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWA6wbsmKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoTP6WDoJCIqDsOE6oZFJyjVC4Pbl5viu03Hkh",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoVt7St92LDzfdtyXCZN81pHvqeShcjA0KuroJ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo20AYNJ1iUgwytplTZ3NzCdcXfuSGjHJW9FE5",
    ],
  },
  {
    slug: "coral-sharm",
    name: "Coral Beach Sharm",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoQXwIJ2bEdAN2SYtehgZwJPrqDVCv94XyMB5z",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKooC8fpMy0HXODjURP6aWmnG1hlE9sNiypdvfr",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKopkxrzMYGuPH375xOmAQUV4DWMbaqJ9knshdy",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoQDGuRVbEdAN2SYtehgZwJPrqDVCv94XyMB5z",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoMYivdJTZRLtViv5Afw7zJWYyGn3c9m2o0OBb",
    ],
  },
  {
    slug: "cove-oman",
    name: "The Cove Oman",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoNT1ZFvpDeCuVHQg4Tcfrw1os2zbhIyJB7KEx",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoIhCGdLgTlInH4jDxaLqJQeB95UZd2krhAVtz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoUjhwANnJUl3GRyE2ih6jquKtSeAcVd4wI0Qg",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoS614tO3y8qcB6ekDnxL7t2AaHzC9ITRVMs1g",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKocKD4TFf4AeVQ8aUkJ7fwnTPztEqiX0Sopd6m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWHO9JpmKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoPVy9wwqA8LHR6kWZ0CQKy7r4ixEAe1VIODT3",
    ],
  },
  {
    slug: "dreamland",
    name: "Dreamland Aqua Park",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWrEvTvmKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6lTT1nVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoKWhyWojdUrwah2H7vRc96XWJjqbxQgB5t14A",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoyBZb60XrAYxzdmVjgpsP86LOhM5CKNnSiytb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKozIhpLzSuCrJZdAD2qUoXnIb8HKW43miEtPBe",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoZm6Ll9cUA3LpYBCJuvn7oebM8sNxq4Oh1Tjl",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo0kEpTzDa7vR6fqLxlnNC5Uo4TWIHSM2esFVt",
    ],
  },
  {
    slug: "fairmont-makkah",
    name: "Fairmont Makkah",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6vQ8hHVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoRLRflIPyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoYNJDStioOTp43itjJGyYsV2PAS8ZzMKg7mXh",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoqTZtyKFwIsUvW8QANLp13Xq0OCzHZMBmtx6n",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoRTezyRPyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoDoEYhPKtTGSY50nBevl9JkXw2hLZPHzxc1IR",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKomgDMxp8Az9kCU6bZsOnvlKwmIxLVWJ71fPoS",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoA2IQhsI6Ti2uqtxQV7Ee8n0k5aI1Dy46YgFs",
    ],
  },
  {
    slug: "fanar-oman",
    name: "Al Fanar Oman",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6k3Rv6VhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo9spU2C4f5HBuWR7heLXoGzcMm1lS8y9rd462",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKouNJRMsLWQpoxB8wY6JUSzLTgjieaFNvyVbKf",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoOVBRnUuWs1Ma2rvQieRHxIVnN9wjJguqA8oz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKobRNBEthcZ4kVF5fpBX80NsPjxCT369rzStoO",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKogW1ju5tYOp3EzU4ZnwhGQeDvAoaFf6CP5d2r",
    ],
  },
  {
    slug: "four-seasons-nile",
    name: "Four Seasons Nile Plaza",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKor2NqUPlJrQhzGdw5Smi6apVgP1EUBTyCskAM",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoIYduiBgTlInH4jDxaLqJQeB95UZd2krhAVtz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6aBooAVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoMqZ1wpTZRLtViv5Afw7zJWYyGn3c9m2o0OBb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKomSfbGI8Az9kCU6bZsOnvlKwmIxLVWJ71fPoS",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoCAOYUhBRHg31aI7PxDs8urdqY20hzBbpyQti",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKonXW8TisoF8WD2YLVgIT9zcahG1e34StEMdPw",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKomQRFsI8Az9kCU6bZsOnvlKwmIxLVWJ71fPoS",
    ],
  },
  {
    slug: "four-seasons-san",
    name: "Four Seasons San Stefano",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo50juFbQWX9d0YkhzgM3DoCNlpVOiZuU2JxAL",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKotLeoSJZO5Ixie0E7aCrF3KzymN162BkLWTqp",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoOYd5GLuWs1Ma2rvQieRHxIVnN9wjJguqA8oz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKonzDFMdoF8WD2YLVgIT9zcahG1e34StEMdPwo",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoaqaPu9ZcihZE5bmBYSutIMw6Lkx9HDj2TOGl",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKok2uuY3UlS7g4a1nNLirvZYOyUWPKeJwcTmGX",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo2gI3Rty1iUgwytplTZ3NzCdcXfuSGjHJW9FE",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1LOn5hI2GBDJ5EhnzkqvUHO8mpwZPgSfrXNA",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoK1e5uEjdUrwah2H7vRc96XWJjqbxQgB5t14A",
    ],
  },
  {
    slug: "four-seasons-sharm",
    name: "Four Seasons Sharm",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoKz1nJwjdUrwah2H7vRc96XWJjqbxQgB5t14A",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1L68uMI2GBDJ5EhnzkqvUHO8mpwZPgSfrXNA",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoR62BWXUPyYsPZxbmrvTI2RHMhcCD9fUa8tzp",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKolDIJtmqO2WcmtyedLjV3SwHRXD8sQZiuh1gI",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1vh0qCI2GBDJ5EhnzkqvUHO8mpwZPgSfrXNA",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKofWI6L0kqmPyJR9eSsVXWMGFItpbcDN5ioE2B",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKokcMGr0UlS7g4a1nNLirvZYOyUWPKeJwcTmGX",
    ],
  },
  {
    slug: "fourseasonscairo",
    name: "Four Seasons Cairo Residence",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKonXeCnPPoF8WD2YLVgIT9zcahG1e34StEMdPw",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoQrZOLYbEdAN2SYtehgZwJPrqDVCv94XyMB5z",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKooZdqwKy0HXODjURP6aWmnG1hlE9sNiypdvfr",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6EzUamVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoPV1YGC4A8LHR6kWZ0CQKy7r4ixEAe1VIODT3",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKomHaDggr8Az9kCU6bZsOnvlKwmIxLVWJ71fPo",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo424VqQzF2OBDRcILbvgxCjsaZKW5i1kMGuf3",
    ],
  },
  {
    slug: "helnan-sharm",
    name: "Helnan Sharm",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoguLzvJftYOp3EzU4ZnwhGQeDvAoaFf6CP5d2",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoz9u4PNSuCrJZdAD2qUoXnIb8HKW43miEtPBe",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo4FEeiYzF2OBDRcILbvgxCjsaZKW5i1kMGuf3",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWxE6asmKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoqeQwvcFwIsUvW8QANLp13Xq0OCzHZMBmtx6n",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoBll2UV7JCRvDNA8b0LQJX9lSTUMyfKqerOI5",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoSrj7Mk3y8qcB6ekDnxL7t2AaHzC9ITRVMs1g",
    ],
  },
  {
    slug: "hilton-green-plaza",
    name: "Hilton Green Plaza",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoLZjIi1nszxb8nrMGymHSQJXtdBkRKE6Y72iZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoJOBBNdrqKu6Te0jsBnX2cgJaxEWlS4D5NtmG",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoDyz6h1KtTGSY50nBevl9JkXw2hLZPHzxc1IR",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoMRIPsLlTZRLtViv5Afw7zJWYyGn3c9m2o0OB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoA2X2wAF6Ti2uqtxQV7Ee8n0k5aI1Dy46YgFs",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoXoRds45abTocvqK4z6t2rpH3RJs5gkfuxhVO",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoPEbmKXA8LHR6kWZ0CQKy7r4ixEAe1VIODT3m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKokRIJleUlS7g4a1nNLirvZYOyUWPKeJwcTmGX",
    ],
  },
  {
    slug: "hilton-hurghada",
    name: "Hilton Hurghada",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoknHJISUlS7g4a1nNLirvZYOyUWPKeJwcTmGX",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoIhQYTYgTlInH4jDxaLqJQeB95UZd2krhAVtz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoycp1KEXrAYxzdmVjgpsP86LOhM5CKNnSiytb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKotIjPpiO5Ixie0E7aCrF3KzymN162BkLWTqpZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKotL8wc6GO5Ixie0E7aCrF3KzymN162BkLWTqp",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKotzpbvnO5Ixie0E7aCrF3KzymN162BkLWTqpZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoIVKB4cgTlInH4jDxaLqJQeB95UZd2krhAVtz",
    ],
  },
  {
    slug: "hilton-king",
    name: "Hilton King's Ranch",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoyQbNWA7XrAYxzdmVjgpsP86LOhM5CKNnSiyt",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoSB4ezm3y8qcB6ekDnxL7t2AaHzC9ITRVMs1g",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo4ZnbROzF2OBDRcILbvgxCjsaZKW5i1kMGuf3",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo2B4XCO1iUgwytplTZ3NzCdcXfuSGjHJW9FE5",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoFmAMOzvSKeMPnwAIsJ7XLO329u6UoBpVRmxz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoMMKXK3TZRLtViv5Afw7zJWYyGn3c9m2o0OBb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo2WQ2dU1iUgwytplTZ3NzCdcXfuSGjHJW9FE5",
    ],
  },
  {
    slug: "hilton-pyramid",
    name: "Hilton Pyramid",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKolvzQUM1qO2WcmtyedLjV3SwHRXD8sQZiuh1g",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoOcDHbfuWs1Ma2rvQieRHxIVnN9wjJguqA8oz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKot9IP9RO5Ixie0E7aCrF3KzymN162BkLWTqpZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoadz231ZcihZE5bmBYSutIMw6Lkx9HDj2TOGl",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoRtptvyPyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoSGClnZM3y8qcB6ekDnxL7t2AaHzC9ITRVMs1",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoVLum352LDzfdtyXCZN81pHvqeShcjA0KuroJ",
    ],
  },
  {
    slug: "hyattoctober",
    name: "Hyatt October",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKofj73gnkqmPyJR9eSsVXWMGFItpbcDN5ioE2B",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKor0sqwplJrQhzGdw5Smi6apVgP1EUBTyCskAM",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKovQLMEJ9otKvndmAXj6EhIzsSPr3iLUqbQ0xu",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoF43OqH3vSKeMPnwAIsJ7XLO329u6UoBpVRmx",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKotC8Q33O5Ixie0E7aCrF3KzymN162BkLWTqpZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6v7BmNVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoQTszPebEdAN2SYtehgZwJPrqDVCv94XyMB5z",
    ],
  },
  {
    slug: "intercontinental-city",
    name: "InterContinental City Stars",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo2WD20q1iUgwytplTZ3NzCdcXfuSGjHJW9FE5",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6p9QtCVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoi9DXR3BRjXKozqUpZCEnigGSNYJtaDk9x7r4",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoLQv01Ynszxb8nrMGymHSQJXtdBkRKE6Y72iZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWjtDPgmKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKovzwSBzK9otKvndmAXj6EhIzsSPr3iLUqbQ0x",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKon41rizoF8WD2YLVgIT9zcahG1e34StEMdPwo",
    ],
  },
  {
    slug: "kempinski-yanbu",
    name: "Kempinski Yanbu",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo9SPzTvC4f5HBuWR7heLXoGzcMm1lS8y9rd46",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoC8BxocRHg31aI7PxDs8urdqY20hzBbpyQtiN",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoVylpMZ2LDzfdtyXCZN81pHvqeShcjA0KuroJ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKolI7cctqO2WcmtyedLjV3SwHRXD8sQZiuh1gI",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoui2dl2LWQpoxB8wY6JUSzLTgjieaFNvyVbKf",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKof803WgkqmPyJR9eSsVXWMGFItpbcDN5ioE2B",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoCWxYFJRHg31aI7PxDs8urdqY20hzBbpyQtiN",
    ],
  },
  {
    slug: "marriottmenahouse",
    name: "Marriott Mena House",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoI75kPOgTlInH4jDxaLqJQeB95UZd2krhAVtz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoPVVbhIpA8LHR6kWZ0CQKy7r4ixEAe1VIODT3",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoRjVeMIPyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoQkvlhcbEdAN2SYtehgZwJPrqDVCv94XyMB5z",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoCEl1NHRHg31aI7PxDs8urdqY20hzBbpyQtiN",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoyqfCZQXrAYxzdmVjgpsP86LOhM5CKNnSiytb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoPMzJawA8LHR6kWZ0CQKy7r4ixEAe1VIODT3m",
    ],
  },
  {
    slug: "meridienhelioplis",
    name: "Le Méridien Heliopolis",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoqwIo1wFwIsUvW8QANLp13Xq0OCzHZMBmtx6n",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWEeThPymKxXUrDPu7v5Zqn9zNTH2bfW8M1Es",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoi4pgh0BRjXKozqUpZCEnigGSNYJtaDk9x7r4",
    ],
  },
  {
    slug: "movenpick-gouna",
    name: "Mövenpick El Gouna",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoMRFVoPTZRLtViv5Afw7zJWYyGn3c9m2o0OBb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoFAUsGVvSKeMPnwAIsJ7XLO329u6UoBpVRmxz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKopZuUZjYGuPH375xOmAQUV4DWMbaqJ9knshdy",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoxglPgk0TOhQuNsB92Z6qe1P4ViRmg8SUjMvA",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKogAelCDtYOp3EzU4ZnwhGQeDvAoaFf6CP5d2r",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoNvB4JypDeCuVHQg4Tcfrw1os2zbhIyJB7KEx",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoLgBZYynszxb8nrMGymHSQJXtdBkRKE6Y72iZ",
    ],
  },
  {
    slug: "movenpick-makkah",
    name: "Mövenpick Makkah",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWYD9ffmKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoYLALslioOTp43itjJGyYsV2PAS8ZzMKg7mXh",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoZ55KHdcUA3LpYBCJuvn7oebM8sNxq4Oh1Tjl",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6JOKMrVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKorJvsgElJrQhzGdw5Smi6apVgP1EUBTyCskAM",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo5haqARzQWX9d0YkhzgM3DoCNlpVOiZuU2JxA",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo0VGZ8eDa7vR6fqLxlnNC5Uo4TWIHSM2esFVt",
    ],
  },
  {
    slug: "movenpick-medinah",
    name: "Mövenpick Medinah",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKopB34rU4YGuPH375xOmAQUV4DWMbaqJ9knshd",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoKGrxuYjdUrwah2H7vRc96XWJjqbxQgB5t14A",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKopqiSfUYGuPH375xOmAQUV4DWMbaqJ9knshdy",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo2g5WqVc1iUgwytplTZ3NzCdcXfuSGjHJW9FE",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKozw8rFUSuCrJZdAD2qUoXnIb8HKW43miEtPBe",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKolr1LCxqO2WcmtyedLjV3SwHRXD8sQZiuh1gI",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoY0wpblioOTp43itjJGyYsV2PAS8ZzMKg7mXh",
    ],
  },
  {
    slug: "radisson-alex",
    name: "Radisson Blu Alexandria",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKouosqy7dLWQpoxB8wY6JUSzLTgjieaFNvyVbK",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoV5mPMq2LDzfdtyXCZN81pHvqeShcjA0KuroJ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoSATb603y8qcB6ekDnxL7t2AaHzC9ITRVMs1g",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoo5mBWpLy0HXODjURP6aWmnG1hlE9sNiypdvf",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo61QTUsdVhaT80Hr7VpegU5nNtZEMSlIyq6dk",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoSox1eE3y8qcB6ekDnxL7t2AaHzC9ITRVMs1g",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoQQN1tobEdAN2SYtehgZwJPrqDVCv94XyMB5z",
    ],
  },
  {
    slug: "ramseshilton",
    name: "Ramses Hilton",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoxfwNhz0TOhQuNsB92Z6qe1P4ViRmg8SUjMvA",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoAs5Ma56Ti2uqtxQV7Ee8n0k5aI1Dy46YgFsK",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoJcupmXrqKu6Te0jsBnX2cgJaxEWlS4D5NtmG",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoUEweXGNnJUl3GRyE2ih6jquKtSeAcVd4wI0Q",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoaMmI7IZcihZE5bmBYSutIMw6Lkx9HDj2TOGl",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoYJqJkA2ioOTp43itjJGyYsV2PAS8ZzMKg7mX",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo43AETTLzF2OBDRcILbvgxCjsaZKW5i1kMGuf",
    ],
  },
  {
    slug: "reef-oasis",
    name: "Reef Oasis",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoST65FH3y8qcB6ekDnxL7t2AaHzC9ITRVMs1g",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo9cgIrx4f5HBuWR7heLXoGzcMm1lS8y9rd462",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoZedhGucUA3LpYBCJuvn7oebM8sNxq4Oh1Tjl",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKogJxA2FtYOp3EzU4ZnwhGQeDvAoaFf6CP5d2r",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoL0T098nszxb8nrMGymHSQJXtdBkRKE6Y72iZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoJZlCEZrqKu6Te0jsBnX2cgJaxEWlS4D5NtmG",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoioQipDBRjXKozqUpZCEnigGSNYJtaDk9x7r4",
    ],
  },
  {
    slug: "rixos-magawish",
    name: "Rixos Magawish",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoKZUN87jdUrwah2H7vRc96XWJjqbxQgB5t14A",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoXefnEe5abTocvqK4z6t2rpH3RJs5gkfuxhVO",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKojcpAr6gaiuRMKHlSC2rzD93pJvBZknAFXTPt",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoR2HlWTPyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoi5GU4hBRjXKozqUpZCEnigGSNYJtaDk9x7r4",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoRsWoGlPyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKogapzTotYOp3EzU4ZnwhGQeDvAoaFf6CP5d2r",
    ],
  },
  {
    slug: "rixos-sharm",
    name: "Rixos Sharm",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoB3cOE2JCRvDNA8b0LQJX9lSTUMyfKqerOI5h",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoroJpLUlJrQhzGdw5Smi6apVgP1EUBTyCskAM",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKouprEZNLWQpoxB8wY6JUSzLTgjieaFNvyVbKf",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoDHUkzYKtTGSY50nBevl9JkXw2hLZPHzxc1IR",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoI5J6e4gTlInH4jDxaLqJQeB95UZd2krhAVtz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKou92aXmLWQpoxB8wY6JUSzLTgjieaFNvyVbKf",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1fwR4hI2GBDJ5EhnzkqvUHO8mpwZPgSfrXNA",
    ],
  },
  {
    slug: "robinson-soma-bay",
    name: "Robinson Soma Bay",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoFrLWiqvSKeMPnwAIsJ7XLO329u6UoBpVRmxz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoLXP3GWnszxb8nrMGymHSQJXtdBkRKE6Y72iZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKocvWd3Nf4AeVQ8aUkJ7fwnTPztEqiX0Sopd6m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoYhbtnrioOTp43itjJGyYsV2PAS8ZzMKg7mXh",
    ],
  },
  {
    slug: "rotana-oman",
    name: "Rotana Oman",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoyQhjOLtXrAYxzdmVjgpsP86LOhM5CKNnSiyt",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKocXCQMVf4AeVQ8aUkJ7fwnTPztEqiX0Sopd6m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoCXXj16RHg31aI7PxDs8urdqY20hzBbpyQtiN",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoVLYCgE2LDzfdtyXCZN81pHvqeShcjA0KuroJ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKozrfXp8SuCrJZdAD2qUoXnIb8HKW43miEtPBe",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoVf1Xdd2LDzfdtyXCZN81pHvqeShcjA0KuroJ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKolANyH1qO2WcmtyedLjV3SwHRXD8sQZiuh1gI",
    ],
  },
  {
    slug: "rotana-sharm",
    name: "Rotana Sharm",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoyzzKbYXrAYxzdmVjgpsP86LOhM5CKNnSiytb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWhFDvqmKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoWYMdd5mKxXUrDPu7v5Zqn9zNTH2bfW8M1EsC",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoPxPqQyA8LHR6kWZ0CQKy7r4ixEAe1VIODT3m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo4PQbuTzF2OBDRcILbvgxCjsaZKW5i1kMGuf3",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoLyd6STXnszxb8nrMGymHSQJXtdBkRKE6Y72i",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKorYGzZalJrQhzGdw5Smi6apVgP1EUBTyCskAM",
    ],
  },
  {
    slug: "semiramis-int",
    name: "Semiramis InterContinental",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKofMPFDWkqmPyJR9eSsVXWMGFItpbcDN5ioE2B",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKobtdNVahcZ4kVF5fpBX80NsPjxCT369rzStoO",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo2gOpM9i1iUgwytplTZ3NzCdcXfuSGjHJW9FE",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKokFnblOUlS7g4a1nNLirvZYOyUWPKeJwcTmGX",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo9Qlw274f5HBuWR7heLXoGzcMm1lS8y9rd462",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKotMGQgBO5Ixie0E7aCrF3KzymN162BkLWTqpZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo4325H4xzF2OBDRcILbvgxCjsaZKW5i1kMGuf",
    ],
  },
  {
    slug: "sheraton-montazah",
    name: "Sheraton Montazah",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6A3h7WVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoRRwfE4PyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoz6cEiMSuCrJZdAD2qUoXnIb8HKW43miEtPBe",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoVIOYLF32LDzfdtyXCZN81pHvqeShcjA0Kuro",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoyGsU9cXrAYxzdmVjgpsP86LOhM5CKNnSiytb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoQWaeUGPbEdAN2SYtehgZwJPrqDVCv94XyMB5",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoqZETKLFwIsUvW8QANLp13Xq0OCzHZMBmtx6n",
    ],
  },
  {
    slug: "sheraton-soma-bay",
    name: "Sheraton Soma Bay",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoYHPKpdioOTp43itjJGyYsV2PAS8ZzMKg7mXh",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoLeg6w1nszxb8nrMGymHSQJXtdBkRKE6Y72iZ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKou4ZXPSLWQpoxB8wY6JUSzLTgjieaFNvyVbKf",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoAqHdy06Ti2uqtxQV7Ee8n0k5aI1Dy46YgFsK",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo19vQHEI2GBDJ5EhnzkqvUHO8mpwZPgSfrXNA",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKorNwFIulJrQhzGdw5Smi6apVgP1EUBTyCskAM",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo6ySrUEVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
    ],
  },
  {
    slug: "sofitel-aswan",
    name: "Sofitel Legend Aswan",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKogq2CBAtYOp3EzU4ZnwhGQeDvAoaFf6CP5d2r",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKobOvCrohcZ4kVF5fpBX80NsPjxCT369rzStoO",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoRKl5lSPyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoSrVGiw3y8qcB6ekDnxL7t2AaHzC9ITRVMs1g",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoiLT8ebBRjXKozqUpZCEnigGSNYJtaDk9x7r4",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoDaYCt35KtTGSY50nBevl9JkXw2hLZPHzxc1I",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoJUdoj1rqKu6Te0jsBnX2cgJaxEWlS4D5NtmG",
    ],
  },
  {
    slug: "sofitel-hurghada",
    name: "Sofitel Hurghada",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoUDhUO7NnJUl3GRyE2ih6jquKtSeAcVd4wI0Q",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoF49cMgGvSKeMPnwAIsJ7XLO329u6UoBpVRmx",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoa5yXY5ZcihZE5bmBYSutIMw6Lkx9HDj2TOGl",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoafpoU3JZcihZE5bmBYSutIMw6Lkx9HDj2TOG",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKomJadlw8Az9kCU6bZsOnvlKwmIxLVWJ71fPoS",
    ],
  },
  {
    slug: "st-regis",
    name: "St. Regis",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo60slwMVhaT80Hr7VpegU5nNtZEMSlIyq6dkB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKon2J1hKoF8WD2YLVgIT9zcahG1e34StEMdPwo",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoVNsRNu2LDzfdtyXCZN81pHvqeShcjA0KuroJ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoVRVq852LDzfdtyXCZN81pHvqeShcjA0KuroJ",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoR2RXy6PyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKomHHOl3Y8Az9kCU6bZsOnvlKwmIxLVWJ71fPo",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoUsqLr0NnJUl3GRyE2ih6jquKtSeAcVd4wI0Q",
    ],
  },
  {
    slug: "staybridge",
    name: "Staybridge Suites",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoqUQYTqFwIsUvW8QANLp13Xq0OCzHZMBmtx6n",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoAAxN8C6Ti2uqtxQV7Ee8n0k5aI1Dy46YgFsK",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo5qD5HDQWX9d0YkhzgM3DoCNlpVOiZuU2JxAL",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoyZwYhSXrAYxzdmVjgpsP86LOhM5CKNnSiytb",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoJ9Zek3rqKu6Te0jsBnX2cgJaxEWlS4D5NtmG",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoqAD6pwFwIsUvW8QANLp13Xq0OCzHZMBmtx6n",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKofcWxvpkqmPyJR9eSsVXWMGFItpbcDN5ioE2B",
    ],
  },
  {
    slug: "steigenberger-aldau",
    name: "Steigenberger Aldau",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo5ox7FrQWX9d0YkhzgM3DoCNlpVOiZuU2JxAL",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoFbd14zvSKeMPnwAIsJ7XLO329u6UoBpVRmxz",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoafq53fIZcihZE5bmBYSutIMw6Lkx9HDj2TOG",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKotLHYw6WO5Ixie0E7aCrF3KzymN162BkLWTqp",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoNXfAtwpDeCuVHQg4Tcfrw1os2zbhIyJB7KEx",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoaKq9J6ZcihZE5bmBYSutIMw6Lkx9HDj2TOGl",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKocXMws3f4AeVQ8aUkJ7fwnTPztEqiX0Sopd6m",
    ],
  },
  {
    slug: "steigenberger-cecil",
    name: "Steigenberger Cecil",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKozhYf1TSuCrJZdAD2qUoXnIb8HKW43miEtPBe",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoF4SJtrevSKeMPnwAIsJ7XLO329u6UoBpVRmx",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoRJH5GxPyYsPZxbmrvTI2RHMhcCD9fUa8tzpn",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKogzrUyDtYOp3EzU4ZnwhGQeDvAoaFf6CP5d2r",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1886gXI2GBDJ5EhnzkqvUHO8mpwZPgSfrXNA",
    ],
  },
  {
    slug: "the-red",
    name: "The Red Sea Hotel",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1dyMzCI2GBDJ5EhnzkqvUHO8mpwZPgSfrXNA",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoJC9BYqrqKu6Te0jsBnX2cgJaxEWlS4D5NtmG",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKo1togWKEI2GBDJ5EhnzkqvUHO8mpwZPgSfrXN",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoD5rpgtKtTGSY50nBevl9JkXw2hLZPHzxc1IR",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoMRCXgMuTZRLtViv5Afw7zJWYyGn3c9m2o0OB",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoudH2WfLWQpoxB8wY6JUSzLTgjieaFNvyVbKf",
    ],
  },
  {
    slug: "tradecenter",
    name: "Trade Center Hotel",
    images: [
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKouonhyhfLWQpoxB8wY6JUSzLTgjieaFNvyVbK",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoxKjuPc10TOhQuNsB92Z6qe1P4ViRmg8SUjMv",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoAhcQ0K6Ti2uqtxQV7Ee8n0k5aI1Dy46YgFsK",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoUm1Tr1NnJUl3GRyE2ih6jquKtSeAcVd4wI0Q",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKolXf3nCqO2WcmtyedLjV3SwHRXD8sQZiuh1gI",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKoPDjU5zA8LHR6kWZ0CQKy7r4ixEAe1VIODT3m",
      "https://2e3n0iobhs.ufs.sh/f/ijFqTGBRjXKolvvGYQVqO2WcmtyedLjV3SwHRXD8sQZiuh1g",
    ],
  },
];
